# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b34eea1d-3deb-4ecf-b1c9-49b11e2ed8fc'
  imageRepository: 'votingapp'
  containerRegistry: 'myvotingappcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

# Agent VM image name
pool:
  name: votingAppAgent
  demands: Agent.Name -equals myVotingAppAgent

stages:
- stage: Build
  displayName: Build the Voting App
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'myVotingAppContainerRegistry'
        repository: 'votingapp/vote'
        command: build
        dockerfile: 'vote/Dockerfile'

- stage: Push
  displayName: Push the Voting App
  jobs:
    - job: Push
      displayName: Push the Voting App
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'myVotingAppContainerRegistry'
          repository: 'votingapp/vote'
          command: push

- stage: Update_bash_script
  displayName: update_Bash_script
  jobs:
    - job: Updating_repo_with_bash
      displayName: updating_repo_using_bash_script
      steps:
      - task: ShellScript@2
        inputs:
          scriptPath: 'vote/updateKubernetesManifests.sh'
          args: 'vote $(imageRepository) $(tag)'