# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - worker/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '261ab38b-35e9-4cbe-9633-d0a62605edb5'
  imageRepository: 'votingapp'
  containerRegistry: 'myvotingappcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
  name: votingAppAgent
  demands: Agent.Name -equals myVotingAppAgent

stages:
- stage: Build
  displayName: Build the Worker Service
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'myVotingAppContainerRegistry'
        repository: 'votingapp/worker'
        command: 'build'
        dockerfilePath: 'worker/Dockerfile'

- stage: Push
  displayName: Push the Worker Service
  jobs:
    - job: Push
      displayName: Push
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'myVotingAppContainerRegistry'
          repository: 'votingapp/worker'
          command: 'push'

